server:
  port: 8090

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: currency-exchange
          uri: lb://currency-exchange
          predicates:
            - Path=/currency-exchange/**

        - id: currency-converter
          uri: lb://currency-converter
          predicates:
            - Path=/currency-converter/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
